// <auto-generated />
namespace Project_mvc.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addyearcolumnstudenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addyearcolumnstudenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805242051293_add year column student table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
